//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrecimientoPaciente
    {
        public int Id { get; set; }
        public int ConsultaId { get; set; }
        public decimal Peso { get; set; }
        public decimal Talla { get; set; }
        public int EdadActual { get; set; }
    
        public virtual Consulta Consulta { get; set; }
    }
}
