//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinicas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClinicasEntities : DbContext
    {
        public ClinicasEntities()
            : base("name=ClinicasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CIE10> CIE10 { get; set; }
        public virtual DbSet<Clinica> Clinica { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<ConsultaEstado> ConsultaEstado { get; set; }
        public virtual DbSet<CrecimientoPaciente> CrecimientoPaciente { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<DiagnosticoCIE10> DiagnosticoCIE10 { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<EstadoConsulta> EstadoConsulta { get; set; }
        public virtual DbSet<ExamenLaboratorio> ExamenLaboratorio { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<OrdenImagen> OrdenImagen { get; set; }
        public virtual DbSet<OrdenLaboratorio> OrdenLaboratorio { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<PagoConsulta> PagoConsulta { get; set; }
        public virtual DbSet<PagoCuenta> PagoCuenta { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
        public virtual DbSet<ReferenciaPaciente> ReferenciaPaciente { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<TipoDiagnostico> TipoDiagnostico { get; set; }
        public virtual DbSet<TipoMedicamento> TipoMedicamento { get; set; }
        public virtual DbSet<TipoPagoConsulta> TipoPagoConsulta { get; set; }
        public virtual DbSet<TipoSangre> TipoSangre { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<uspReportePacientes_Result> uspReportePacientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspReportePacientes_Result>("uspReportePacientes");
        }
    }
}
